configfile: '../config/config.yaml'
print(config)

##### Target rules #####

import pandas as pd
import os

samples = pd.read_csv ( config['Sample_names'] )

# Create arrays of the sample names
samples = samples['Sample_name'].values
print(samples)


rule all:
    input:
        vcf="variants/GT_SNP.table",
        dicti= config['ref']['dict'],
        fai= config['ref']['fai'],
        GtoA3p=expand ("results/{sample}/3pGtoA_freq.txt", sample = samples),
        dbtype="humandb/" + config['params']['annotation']['buildver'] + "_" + config['params']['annotation']['dbtype']+".txt",
        bam_idx=expand ("marked_dedup/{sample}_ref.bam.bai", sample = samples),
        valid = expand ("logs/validate_bam/{sample}.summary.txt", sample = samples)


##### Modules #####
###################
include: "rules/pre_processing.smk"     
include: "rules/mapping.smk"
include: "rules/post_mapping.smk"
#include: "rules/angsd.smk"

## For classic SNP calling on not so damaged DNA
include: "rules/variants_calling.smk"
include: "rules/annotationHuman.smk"    # WARNING! For annotation of SNP using the ANNOVAR premade database on hg38.
include: "rules/variants_to_table.smk"